---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без нее
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Корзина должна храниться в сессии браузера
  - Сайт должен быть SPA-приложение, которое не перезагружает страницу
implicit:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
